### ISSUE TITLE
Postprocess (nzbget.py) error line 60 (timeout)

### ISSUE THREAD

**Issue by MartinAyla** [nosmokingbandit/watcher#142]
Hi

With the latest nzbget.py script I see this error in NZBGet:

``
INFO Thu Jan 12 2017 12:08:13	nzbget: TypeError: __init__() got an unexpected keyword argument 'timeout'
INFO	Thu Jan 12 2017 12:08:13	nzbget: request = urllib2.Request(url, post_data, headers={'User-Agent': 'Mozilla/5.0'}, timeout=600)
INFO	Thu Jan 12 2017 12:08:13	nzbget: File "/home/martin/nzbget/scripts/nzbget.py", line 60, in <module>
``

EDIT: removing the "timeout=600" makes it work again.

**Comment by vertigo235** [comment]
Looks like the correct usage would be 
request = urllib2.Request(url, post_data, headers={'User-Agent': 'Mozilla/5.0'}, timeout=600)
response = json.loads(urllib2.urlopen(request, timeout=600).read())

**Comment by vertigo235** [comment]
I tested this change and it works for me, created pull request https://github.com/nosmokingbandit/watcher/pull/145

**Comment by nosmokingbandit** [comment]
Fixed in commit https://github.com/nosmokingbandit/watcher/commit/05995e2191227d6f8ff17f7f66d677ffcd2b4df3

Remember to change your post-scripts and reconfigure.

**Comment by bleomycin** [comment]
@nosmokingbandit 

Sorry this is still failing for me, updated to  d6ce824, grabbed latest post processing script. I'm using the [proxy] feature if it makes any difference, but i have the appropriate settings in nzbget according to the wiki to compensate. I also tested with proxy set to false and settings changed in nzbget to reflect, no change. Debian Jessie, Mono version 4.6.2

```
Sun Jan 15 12:31:26 2017        INFO    watcher: Traceback (most recent call last):
Sun Jan 15 12:31:26 2017        INFO    watcher:   File "/home/nzbget/nzbget/scripts/watcher.py", line 61, in <module>
Sun Jan 15 12:31:26 2017        INFO    watcher:     response = json.loads(urllib2.urlopen(request, timeout=600).read())
Sun Jan 15 12:31:26 2017        INFO    watcher:   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
Sun Jan 15 12:31:26 2017        INFO    watcher:     return opener.open(url, data, timeout)
Sun Jan 15 12:31:26 2017        INFO    watcher:   File "/usr/lib/python2.7/urllib2.py", line 437, in open
Sun Jan 15 12:31:26 2017        INFO    watcher:     response = meth(req, response)
Sun Jan 15 12:31:26 2017        INFO    watcher:   File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
Sun Jan 15 12:31:26 2017        INFO    watcher:     'http', request, response, code, msg, hdrs)
Sun Jan 15 12:31:26 2017        INFO    watcher:   File "/usr/lib/python2.7/urllib2.py", line 475, in error
Sun Jan 15 12:31:26 2017        INFO    watcher:     return self._call_chain(*args)
Sun Jan 15 12:31:26 2017        INFO    watcher:   File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
Sun Jan 15 12:31:26 2017        INFO    watcher:     result = func(*args)
Sun Jan 15 12:31:26 2017        INFO    watcher:   File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
Sun Jan 15 12:31:26 2017        INFO    watcher:     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
Sun Jan 15 12:31:26 2017        INFO    watcher: urllib2.HTTPError: HTTP Error 500: Internal Server Error
Sun Jan 15 12:31:26 2017        ERROR   Post-process-script watcher.py for something.Watcher failed (terminated with unknown status)
```

**Comment by nosmokingbandit** [comment]
Get me the logs from Watcher and I can figure this out.

**Comment by SpencerCarstens** [comment]
This seems to be related to an error parsing the name of the file.

```
INFO 2017-01-04 17:01:44,301 core.postprocessing.GET: #################################
INFO 2017-01-04 17:17:13,220 core.postprocessing.GET: #################################
INFO 2017-01-04 17:17:13,220 core.postprocessing.GET: Post-processing request received.
INFO 2017-01-04 17:17:13,220 core.postprocessing.GET: #################################
INFO 2017-01-04 17:17:13,220 core.postprocessing.get_filename: Finding movie file name.
INFO 2017-01-04 17:17:13,221 core.postprocessing.get_filename: Post-processing file C:\ProgramData\NZBGet\complete\Movies\Alice.Through.the.Looking.Glass.2016.1080p.BluRay.REMUX.AVC.DTS-HD.MA.7.1-PrivateHD\20xqW8A8ob1cW.mkv.
INFO 2017-01-04 17:17:13,221 core.postprocessing.GET: Parsing release name for information.
INFO 2017-01-04 17:17:13,221 core.postprocessing.GET: Gathering release information.
INFO 2017-01-04 17:17:13,221 core.postprocessing.get_movie_info: Searching local database for guid.
INFO 2017-01-04 17:17:13,221 core.sqldb.get_single_search_result: Retreving search result details for https://dognzb.cr/fetch/d418bc649ba84d322f974741348ea6f0/d37a2a0d7537eceb3e8f21b4ab88206a.
INFO 2017-01-04 17:17:13,223 core.postprocessing.get_movie_info: Searching local database for downloadid.
INFO 2017-01-04 17:17:13,223 core.sqldb.get_single_search_result: Retreving search result details for 811.
INFO 2017-01-04 17:17:13,223 core.postprocessing.get_movie_info: Unable to find local data for release. Searching OMDB.
INFO 2017-01-04 17:17:13,223 core.postprocessing.get_movie_info: Searching omdb for xqW8A8ob1cW 
INFO 2017-01-04 17:17:14,359 core.postprocessing.get_movie_info: Nothing found in OMDB.
ERROR 2017-01-04 17:17:14,359 cherrypy.error.72997968.error: [04/Jan/2017:17:17:14] HTTP 
Traceback (most recent call last):
  File "D:\watcher\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "D:\watcher\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "D:\watcher\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "D:\watcher\core\postprocessing.py", line 78, in GET
    data.update(self.get_movie_info(data))
TypeError: 'NoneType' object is not iterable
INFO 2017-01-04 17:17:14,361 cherrypy.error.72997968.error: [04/Jan/2017:17:17:14] HTTP 
Request Headers:
  HOST: localhost:9090
  CONNECTION: close
  Remote-Addr: 127.0.0.1
  USER-AGENT: Mozilla/5.0
  ACCEPT-ENCODING: identity
```

**Comment by nosmokingbandit** [comment]
Sorry it took a while to get back to you, I've been working on torrent
support, which is really time consuming.

Anyway, it looks like this was processed on the 4th (04/Jan/2017), which
makes sense. On the 5th I added a method to parse the folder name if the
filename doesn't have any useful information.

https://github.com/nosmokingbandit/watcher/commit/731db4d2055356bef9b9175258dd7c6d7730f514

Let me know if the problem persists.
