### ISSUE TITLE
Not fully imported IMDb Watchlist

### ISSUE THREAD

**Issue by ItsMeMike** [nosmokingbandit/watcher#196]
#### What happened?
Watchlist defined in settings, contains 50 titles. Watcher only imported 30.
#### What was supposed to happen?
It should import everything.
#### How can I reproduce this?
Set up a new environment ofcourse, and place in settings:
 http://rss.imdb.com/user/ur50025327/watchlist
I have it setup to check ever 20 minutes (to see if it imported more after an hour or 2)
#### Logs show this error:
```
Exception in thread Thread-20:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "C:\watcher\core\plugins\taskscheduler.py", line 114, in task
    self.func()
  File "C:\watcher\core\scheduler.py", line 181, in sync_rss
    imdb_rss.get_rss(rss_url)
  File "C:\watcher\core\rss\imdb.py", line 51, in get_rss
    self.sync_new_movies(movies)
  File "C:\watcher\core\rss\imdb.py", line 149, in sync_new_movies
    self.ajax.add_wanted_movie(json.dumps(movie_info))
  File "C:\watcher\core\ajax.py", line 93, in add_wanted_movie
    data['year'] = data['release_date'][:4]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by Elfman72** [comment]
I just noticed that not all my watchlist items were importing too.  Some of them are but not all.  No imdb errors in the log though.

**Comment by nosmokingbandit** [comment]
I just pushed some changes to the imdb sync method. Update to 0ce098e30a10d94db635c5d1f489716d8d0a9db7 and let me know what happens.

**Comment by ItsMeMike** [comment]
Current version hash: f084e75

Error still occurs.
'''
Exception in thread Thread-21:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "C:\watcher\core\cp_plugins\taskscheduler.py", line 114, in task
    self.func()
  File "C:\watcher\core\scheduler.py", line 181, in sync_rss
    imdb_rss.get_rss(rss_url)
  File "C:\watcher\core\rss\imdb.py", line 52, in get_rss
    self.sync_new_movies(movies, list_id)
  File "C:\watcher\core\rss\imdb.py", line 148, in sync_new_movies
    self.ajax.add_wanted_movie(json.dumps(movie_info))
  File "C:\watcher\core\ajax.py", line 93, in add_wanted_movie
    data['year'] = data['release_date'][:4]
TypeError: 'NoneType' object has no attribute '__getitem__'
'''

**Comment by nosmokingbandit** [comment]
Try it again after 5a54d501488daa8609be65eebf92bb81adf0db2c.

I think it is trying to add a movie that has no release date info at all.

**Comment by ItsMeMike** [comment]
That was it! It tried to add Cyborg, Gambit & Justice League Part Two. These do not have a release date in IMDb yet.
